name: ubuntu build
run-name: build runner on ubuntu 🚀

# 触发CI条件
on:
  push:
    # 当下面文件发生变化时, 触发CI
    paths:
      - 'setup.py'
      - 'packages.json'
      - '.github/workflows/ubuntu-build.yaml'

  pull_request:
    # 当下面分支PR时, 触发CI
    branches:
      - main
    types: [opened, synchronize, reopened, closed]

  # # 用于在一个工作流完成后触发另一个工作流
  # # 例如一个deploy job需要等待build job结束后才会触发
  # workflow_run:
  #   workflows: ["CI"] # job name
  #   types:
  #     - completed

jobs:
  build-amd-ubuntu:
    # 并行
    strategy:
      matrix:
        os: ["16.04", "18.04", "20.04", "22.04"]

    # # 非关闭PR触发
    # if: github.event.action != 'closed'
    # github actions docker image
    runs-on: ubuntu-latest
    # docker in docker 因为Github提供的镜像不满足需求, 所以需要拉取dockerhub上的镜像
    container:
      # dockerhub镜像
      image: docker://ubuntu:${{ matrix.os }}
      # # 挂载
      # options: --volume ${{ github.workspace }}:/workspace/${{ github.repository }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v1 # https://github.com/actions/checkout/issues/1590
        with:
          fetch-depth: 1

      # 安装依赖
      - name: Install
        # 非交互式
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt update
          apt install -y pkg-config wget unzip python3-dev git cmake g++

      # 编译
      - name: Build
        run: |
          bash -c "python3 setup.py && source install/setup.bash"

      - name: Test
        run: |
          bash -c "source install/setup.bash && source install1/setup.1/env/setup.bash && source install2/setup.2/env/setup.bash"

  build-arm-ubuntu:
    # 关闭PR时才触发
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu18.04
          - arch: aarch64
            distro: ubuntu20.04
          - arch: aarch64
            distro: ubuntu_latest # ubuntu 24.04

    steps:
      - name: Check out repository code
        uses: actions/checkout@v1 # https://github.com/actions/checkout/issues/1590
        with:
          fetch-depth: 1
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}

          install: |
            apt update
            apt install -y lsb-release

          run: |
            echo "-----------------------"
            uname -a
            lsb_release -a
            echo "-----------------------"
            ls # 当前仓库根目录 .git

